//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gibdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatrgoryOfLicense
    {
        public int id { get; set; }
        public int LicenseId { get; set; }
        public int LicenseCategoryId { get; set; }
    
        public virtual License License { get; set; }
        public virtual LicenseCategory LicenseCategory { get; set; }
    }
}
