//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gibdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public License()
        {
            this.CatrgoryOfLicense = new HashSet<CatrgoryOfLicense>();
        }
    
        public int Id { get; set; }
        public System.DateTime LicenseDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public string LicenseSeries { get; set; }
        public int LicenseNumber { get; set; }
        public int DriverId { get; set; }
        public int LicenseStateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatrgoryOfLicense> CatrgoryOfLicense { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual LicenseState LicenseState { get; set; }
    }
}
