//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gibdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleAccident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleAccident()
        {
            this.CarofAccident = new HashSet<CarofAccident>();
            this.DriverOfAccident = new HashSet<DriverOfAccident>();
            this.PhotoOfVehicleAccident = new HashSet<PhotoOfVehicleAccident>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string RowOfRoad { get; set; }
        public string TrafficLane { get; set; }
        public int VictimsCount { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarofAccident> CarofAccident { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverOfAccident> DriverOfAccident { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoOfVehicleAccident> PhotoOfVehicleAccident { get; set; }
    }
}
